#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-plexus-interpolation
Version  : 1.11
Release  : 1
URL      : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
Source0  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
Source1  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.pom
Source2  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.jar
Source3  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom
Source4  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
Source5  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.pom
Source6  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.jar
Source7  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.pom
Source8  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.22/plexus-interpolation-1.22.pom
Source9  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.jar
Source10  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.pom
Source11  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
Source12  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-plexus-interpolation-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-plexus-interpolation package.
Group: Data

%description data
data components for the mvn-plexus-interpolation package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.12
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.12
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.15
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.15

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.15
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.15

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.22
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.22

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.jar
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.jar
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.22/plexus-interpolation-1.22.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.jar
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.pom
